classDiagram
    class Dispatcher
    Dispatcher: # string NO_EMPLOYEES_AVILABLE
    Dispatcher: - Operator[] operators
    Dispatcher: - Supervisor[] supervisors
    Dispatcher: - Director[] directors
    Dispatcher: - dispatchCall()
    Dispatcher: + findEmployer()

